### ISSUE TITLE
go routine created on flush logs has a leak.

### ISSUE THREAD

**Issue by Himanshuxone** [kubernetes/klog#188]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
After running test cases found out that there is a go routine leak in klog.go
```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 19 in state chan receive, with github.ibm.com/riaas/regional-storage/vendor/k8s.io/klog.(*loggingT).flushDaemon on top of the stack:
goroutine 19 [chan receive]:
github.ibm.com/riaas/regional-storage/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x240e2c0)
	/Users/himanshuchaudhary/go/src/github.ibm.com/riaas/regional-storage/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by github.ibm.com/riaas/regional-storage/vendor/k8s.io/klog.init.0
	/Users/himanshuchaudhary/go/src/github.ibm.com/riaas/regional-storage/vendor/k8s.io/klog/klog.go:411 +0xd6
```

**Comment by Monokaix** [comment]
@fejta-bot @Himanshuxone leak problem seems still exists, can we reopet it and fix?

**Comment by Himanshuxone** [comment]
@Monokaix yes I have installed the new version of Klogs I can see the go routines are still leaking
