### ISSUE TITLE
klog.SetOutput(ioutil.Discard) doesn't remove output

### ISSUE THREAD

**Issue by miekg** [kubernetes/klog#87]
/kind bug

**What steps did you take and what happened:**
calling `klog.SetOutput(ioutil.Discard` doesn't remove logging output.

**What did you expect to happen:**
No logging ouput.

**Anything else you would like to add:**
In https://github.com/coredns/coredns/pull/3055 I want to test various things, but not clutter the output to much, so I call `	klog.SetOutput(ioutil.Discard)`, but the screen this is full off:

~~~~
0810 07:23:54.827224    2826 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Pod: Get https://127.0.0.1:443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DUnknown&limit=500&resourceVersion=0: dial tcp 127.0.0.1:443: connect: connection refused
E0810 07:23:54.827224    2826 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Pod: Get https://127.0.0.1:443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DUnknown&limit=500&resourceVersion=0: dial tcp 127.0.0.1:443: connect: connection refused
E0810 07:23:54.827224    2826 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Pod: Get https://127.0.0.1:443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DUnknown&limit=500&resourceVersion=0: dial tcp 127.0.0.1:443: connect: connection refused
E0810 07:23:54.827224    2826 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Pod: Get https://127.0.0.1:443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DUnknown&limit=500&resourceVersion=0: dial tcp 127.0.0.1:443: connect: connection refused
E0810 07:23:54.829765    2826 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Pod: Get https://127.0.0.1:443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DUnknown&limit=500&resourceVersion=0: dial tcp 127.0.0.1:443: connect: connection refused
E0810 07:23:54.829765    2826 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Pod: Get https://127.0.0.1:443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DUnknown&limit=500&resourceVersion=0: dial tcp 127.0.0.1:443: connect: connection refused
E0810 07:23:54.829765    2826 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Pod: Get https://127.0.0.1:443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DUnknown&limit=500&resourceVersion=0: dial tcp 127.0.0.1:443: connect: connection refused
E0810 07:23:54.829765    2826 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Pod: Get https://127.0.0.1:443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DUnknown&limit=500&resourceVersion=0: dial tcp 127.0.0.1:443: connect: connection refused
~~~

**Comment by miekg** [comment]
Wait I'm holding it wrong it needs an `*os.File`.

**Comment by yqwang-ms** [comment]
Seems SetOutput only set the logging destination for file.
To also impact the std stream, such as stderr, does below work?
```
	klog.InitFlags(flag.CommandLine)
	flag.Parse()
	flag.Set("logtostderr", "false")
	flag.Set("alsologtostderr", "false")
	klog.SetOutput(ioutil.Discard)
```
Change current behaiour of SetOutput may be a breaking change, I suggest if we can provide another interface, or use a flag to tell if need to change behaiour.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [kubernetes/klog] klog.SetOutpu..." ]
>Seems SetOutput only set the logging destination for file.
>To also impact the std stream, such as stderr, does below work?
>```
>	klog.InitFlags(flag.CommandLine)
>	flag.Parse()
>	flag.Set("logtostderr", "false")
>	flag.Set("alsologtostderr", "false")
>	klog.SetOutput(ioutil.Discard)
>```
>Change current behaiour of SetOutput may be a breaking change, I suggest if we can provide another interface, or use a flag to tell if need to change behaiour.

hmm, this panics:

~~~
=== RUN   TestReadme
/tmp/go-build150470533/b001/test.test flag redefined: log_dir
--- FAIL: TestReadme (0.06s)
panic: /tmp/go-build150470533/b001/test.test flag redefined: log_dir [recovered]
	panic: /tmp/go-build150470533/b001/test.test flag redefined: log_dir

goroutine 5 [running]:
testing.tRunner.func1(0xc000572200)
~~~

**Comment by DirectXMan12** [comment]
hmm... are you consuming something that already calls `klog.InitFlags`?

**Comment by yqwang-ms** [comment]
Looks like klog conflicts with glog, so check repo readme to resolve it?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [kubernetes/klog] klog.SetOutpu..." ]
>Looks like klog conflicts with glog, so check repo readme to resolve it?

yep, sorry my mistake, this code got called multiple times - but I was happy to 
remove this flag fiddling from our code in the first place. Not thrilled to 
re-add it.

Also it doesn't discard the output :-(

**Comment by liztio** [comment]
Bumping this, this is still an issue. 

Here's my minimal reproduction:

```go
package main

import (
	"bytes"
	//"flag"
	"fmt"

	"k8s.io/klog"
	"k8s.io/klog/klogr"
)

func main() {
	klog.InitFlags(nil)
	//flag.Set("logtostderr", "false")

	buf := new(bytes.Buffer)

	l := klogr.New()

	klog.SetOutput(buf)

	l.Info("a log line", "key", "value")

	fmt.Printf("Logs: <<<\n%s\n>>>\n", buf.String())
}
```
As written, this prints to stdout:
```
I1009 15:08:19.649067   27080 main.go:18]  "msg"="a log line"  "key"="value"
Logs: <<<

>>>
```

If you uncomment flag.Set and the flag import, this behaves as expected:
```
Logs: <<<
I1009 15:19:19.877580    2926 main.go:18]  "level"=0 "msg"="a log line"  "key"="value"

>>>
```

This makes writing tests around logging very difficult. I think at least a `LogToFile()` or similar method would be useful here

**Comment by vanou** [comment]
> [ Quoting <notifications@github.com> in "Re: [kubernetes/klog] klog.SetOutpu..." ]
> Seems SetOutput only set the logging destination for file. To also impact the std stream, such as stderr, does below work? ``` klog.InitFlags(flag.CommandLine) flag.Parse() flag.Set("logtostderr", "false") flag.Set("alsologtostderr", "false") klog.SetOutput(ioutil.Discard) ``` Change current behaiour of SetOutput may be a breaking change, I suggest if we can provide another interface, or use a flag to tell if need to change behaiour.
> hmm, this panics: ~~~ === RUN TestReadme /tmp/go-build150470533/b001/test.test flag redefined: log_dir --- FAIL: TestReadme (0.06s) panic: /tmp/go-build150470533/b001/test.test flag redefined: log_dir [recovered] panic: /tmp/go-build150470533/b001/test.test flag redefined: log_dir goroutine 5 [running]: testing.tRunner.func1(0xc000572200) ~~~

(TH

**Comment by phelian** [comment]
For what it's worth, I ran into this issue today and I solved it like this

```
// TurnOffKlog supresses leaderelector.go's usage of klog
func TurnOffKlog() {
	klog.SetLogger(&EmptyLogger{})
}

// EmptyLogger implements logr.Logging
type EmptyLogger struct{}

// Enabled always returns false
func (e *EmptyLogger) Enabled() bool {
	return false
}

// Info does nothing
func (e *EmptyLogger) Info(msg string, keysAndValues ...interface{}) {}

// Error does nothing
func (e *EmptyLogger) Error(err error, msg string, keysAndValues ...interface{}) {}

// V returns itself
func (e *EmptyLogger) V(level int) logr.Logger {
	return e
}

// WithValues returns itself
func (e *EmptyLogger) WithValues(keysAndValues ...interface{}) logr.Logger {
	return e
}

// WithName returns itself
func (e *EmptyLogger) WithName(name string) logr.Logger {
	return e
}
```

**Comment by pohly** [comment]
This worked for me:
```
	klog.SetOutput(io.Discard)
	flags := &flag.FlagSet{}
	klog.InitFlags(flags)
	flags.Set("logtostderr", "false")
```

It uses a custom flag set to avoid interactions with the normal flags of the program. `flags.Set` then suppresses the default output to stderr.

**Comment by pohly** [comment]
/close

I consider this resolved, please reopen if it isn't.

**Comment by zparnold** [comment]
I'm not re-opening this thread, just leaving this here in case it helps someone else (or me if I search for it again in the future):

``` go
flags := &flag.FlagSet{}
klog.InitFlags(flags)
flags.Set("logtostderr", "false")
flags.Set("alsologtostderr", "false")
flags.Set("stderrthreshold", "4")
```

This is to avoid this line from `klog`:
``` go 
	if l.toStderr || l.alsoToStderr || s >= l.stderrThreshold.get() { ...

```

I didn't explicitly have to "discard" the output, but error messages (intentional in tests) were making it to the logs.
